name: in_app_face_recognition
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Try these in order of preference:
  # Option 1: Latest version
  tflite_flutter: ^0.11.0

  # Option 2: If above fails, try stable version
  # tflite_flutter: ^0.10.1

  # Option 3: Alternative package (if official doesn't work)
  # tflite_flutter_helper: ^0.3.1

  image: ^4.0.17
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Add this if you still have issues:
dependency_overrides:
  # Force compatible version of typed_data
  typed_data: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/