name: in_app_face_recognition
description: "A Flutter face recognition app with camera support."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Image processing
  image: ^4.0.17
  # Camera and image picker
  camera: ^0.10.5+5
  image_picker: ^1.1.2
  # File system access
  path_provider: ^2.1.1
  # Permissions
  permission_handler: ^11.0.1
  # Additional utilities
  path: ^1.9.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/